### ISSUE TITLE
Problem upgrading from 1.1.0 to 1.2.1

### ISSUE THREAD

**Issue by lhein** [jsdevel/node-find-java-home#33]
When upgrading from 1.1.0 to 1.2.1 I get the below build issue for my [vscode extension](https://github.com/jboss-fuse/vscode-atlasmap/pull/609). Any idea whats wrong?

```
npm run vscode:prepublish


> atlasmap-viewer@0.0.8 vscode:prepublish /home/circleci/vscode-atlasmap
> tsc -p ./

node_modules/find-java-home/dist/index.d.ts:11:9 - error TS2323: Cannot redeclare exported variable 'promise'.

11     var promise: Promise<string | null>;
           ~~~~~~~

node_modules/find-java-home/dist/index.d.ts:15:9 - error TS2323: Cannot redeclare exported variable 'promise'.

15     var promise: Promise<string | null>;
           ~~~~~~~


Found 2 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! atlasmap-viewer@0.0.8 vscode:prepublish: `tsc -p ./`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the atlasmap-viewer@0.0.8 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2021-06-02T05_09_04_371Z-debug.log


Exited with code exit status 2

```

**Comment by jsdevel** [comment]
please submit a PR
